version: 2.1

commands:
  yarn_install:
    steps:
      - run:
          name: install
          command: |
            if [ ! -d node_modules ]; then
              yarn install --frozen-lockfile
            fi

jobs:
  lint_and_test:
    resource_class: small
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: frontend-dependencies-{{ checksum "yarn.lock" }}
      - yarn_install
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test src/_circleci

workflows:
  version: 2
  build:
    jobs:
      - lint_and_test
